/*
 * This source file was generated by the Gradle 'init' task
 */
package com.poc.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appExtendsApplication() {
        // Verificar que App extiende de javafx.application.Application
        assertTrue(javafx.application.Application.class.isAssignableFrom(App.class), 
                   "App should extend javafx.application.Application");
    }
}
